name: Build Silk!

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: set env
        run: echo "BUILD_NUM=$(( 160 + ${{ github.run_number }} ))" >> $GITHUB_ENV
      - name: build the image
        run: |
          docker buildx build \
          --tag velvetthepanda/silk:$BUILD_NUM \
          --platform linux/amd64,linux/arm64 .
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: push the image
        run: |
          docker buildx build --push \
            --tag velvetthepanda/silk:$BUILD_NUM \
            --platform linux/amd64,linux/arm64 .
